// cardsData.js
const cards = [
    { question: "What is the supreme law of the land?", answer: "The Constitution" },
    { question: "What does the Constitution do?", answer: "▪ sets up the government\n▪ defines the government\n▪ protects basic rights of Americans" },
    { question: "The idea of self-government is in the first three words of the Constitution. What are these words?", answer: "We the People" },
    { question: "What is an amendment?", answer: "▪ a change (to the Constitution)\n▪ an addition (to the Constitution)" },
    { question: "What do we call the first ten amendments to the Constitution?", answer: "the Bill of Rights" },
    { question: "What is one right or freedom from the First Amendment?", answer: "▪ speech\n▪ religion\n▪ assembly\n▪ press\n▪ petition the government" },
    { question: "How many amendments does the Constitution have?", answer: "twenty-seven (27)" },
    { question: "What did the Declaration of Independence do?", answer: "▪ announced our independence (from Great Britain)\n▪ declared our independence (from Great Britain)\n▪ said that the United States is free (from Great Britain)" },
    { question: "What are two rights in the Declaration of Independence?", answer: "▪ life\n▪ liberty\n▪ pursuit of happiness" },
    { question: "What is freedom of religion?", answer: "You can practice any religion, or not practice a religion." },
    { question: "What is the economic system in the United States?", answer: "▪ capitalist economy\n▪ market economy" },
    { question: "What is the 'rule of law'?", answer: "▪ Everyone must follow the law.\n▪ Leaders must obey the law.\n▪ Government must obey the law.\n▪ No one is above the law" },
    { question: "Name one branch or part of the government.", answer: "▪ Congress\n▪ legislative\n▪ President\n▪ executive\n▪ the courts\n▪ judicial" },
    { question: "What stops one branch of government from becoming too powerful?", answer: "▪ checks and balances\n▪ separation of powers" },
    { question: "Who is in charge of the executive branch?", answer: "the President" },
    { question: "Who makes federal laws?", answer: "▪ Congress\n▪ Senate and House (of Representatives)\n▪ (U.S. or national) legislature" },
    { question: "What are the two parts of the U.S. Congress?", answer: "the Senate and House (of Representatives)" },
    { question: "How many U.S. Senators are there?", answer: "one hundred (100)" },
    { question: "We elect a U.S. Senator for how many years?", answer: "six (6)" },
    { question: "Who is one of your state’s U.S. Senators now?", answer: "▪ John Cornyn\n ▪ Ted Cruz]" },
    { question: "The House of Representatives has how many voting members?", answer: "four hundred thirty-five (435)" },
    { question: "We elect a U.S. Representative for how many years?", answer: "two (2)" },
    { question: "Name your U.S. Representative.", answer: "▪ Keith Seif (3rd, Collin)\n▪ Pat Fallon (4th, Collin)\n▪ Jake Ellzey (6th, Tarrant)\n▪ Kay Granger (12th, Denton/Tarrant)\n▪ Beth Van Duyne (24th, Tarrant)\n▪ Michael Burgess (26th, Denton)\n▪ Jasmine Crocket (30th, Dallas)\n▪ Colin Allred (32nd, Dallas)\n▪ Marc Veasey (33rd, Dallas)" },
    { question: "Who does a U.S. Senator represent?", answer: "all people of the state" },
    { question: "Why do some states have more Representatives than other states?", answer: "▪ (because of) the state’s population\n▪ (because) they have more people\n▪ (because) some states have more people" },
    { question: "We elect a President for how many years?", answer: "four (4)" },
    { question: "In what month do we vote for President?", answer: "November" },
    { question: "What is the name of the President of the United States now?", answer: "Joe Biden" },
    { question: "What is the name of the Vice President of the United States now?", answer: "Kamala Harris" },
    { question: "If the President can no longer serve, who becomes President?", answer: "the Vice President" },
    { question: "If both the President and the Vice President can no longer serve, who becomes President?", answer: "the Speaker of the House" },
    { question: "Who is the Commander in Chief of the military?", answer: "the President" },
    { question: "Who signs bills to become laws?", answer: "the President" },
    { question: "Who vetoes bills?", answer: "the President" },
    { question: "What does the President’s Cabinet do?", answer: "advises the President" },
    { question: "What are two Cabinet-level positions?", answer: "▪ Secretary of Agriculture\n▪ Secretary of Commerce\n▪ Secretary of Defense\n▪ Secretary of Education\n▪ Secretary of Energy\n▪ Secretary of Health and Human Services\n▪ Secretary of Homeland Security\n▪ Secretary of Housing and Urban Development\n▪ Secretary of the Interior\n▪ Secretary of Labor\n▪ Secretary of State\n▪ Secretary of Transportation\n▪ Secretary of the Treasury\n▪ Secretary of Veterans Affairs\n▪ Attorney General\n▪ Vice President" },
    { question: "What does the judicial branch do?", answer: "▪ reviews laws\n▪ explains laws\n▪ resolves disputes (disagreements)\n▪ decides if a law goes against the Constitution" },
    { question: "What is the highest court in the United States?", answer: "the Supreme Court" },
    { question: "How many justices are on the Supreme Court?", answer: " Nine (9)" },
    { question: "Who is the Chief Justice of the United States now?", answer: "John Roberts" },
    { question: "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?", answer: "▪ to print money\n▪ to declare war\n▪ to create an army\n▪ to make treaties" },
    { question: "Under our Constitution, some powers belong to the states. What is one power of the states?", answer: "▪ provide schooling and education\n▪ provide protection (police)\n▪ provide safety (fire departments)\n▪ give a driver’s license\n▪ approve zoning and land use" },
    { question: "Who is the Governor of your state now?", answer: "Greg Abbott" },
    { question: "What is the capital of your state?", answer: "Austin, TX" },
    { question: "What are the two major political parties in the United States?", answer: "Democratic and Republican" },
    { question: "What is the political party of the President now?", answer: "The Democratic Party." },
    { question: "What is the name of the Speaker of the House of Representatives now?", answer: "Mike Johnson" },
    { question: "There are four amendments to the Constitution about who can vote. Describe one of them.", answer: "▪ Citizens eighteen (18) and older (can vote).\n▪ You don’t have to pay (a poll tax) to vote.\n▪ Any citizen can vote. (Women and men can vote.)\n▪ A male citizen of any race (can vote)." },
    { question: "What is one responsibility that is only for United States citizens?", answer: "▪ serve on a jury\n▪ vote in a federal election" },
    { question: "Name one right only for United States citizens.", answer: "▪ vote in a federal election\n▪ run for federal office" },
    { question: "What are two rights of everyone living in the United States?", answer: "▪ freedom of expression\n▪ freedom of speech\n▪ freedom of assembly\n▪ freedom to petition the government\n▪ freedom of religion\n▪ the right to bear arms" },
    { question: "What do we show loyalty to when we say the Pledge of Allegiance?", answer: "▪ the United States\n▪ the flag" },
    { question: "What is one promise you make when you become a United States citizen?", answer: "▪ give up loyalty to other countries\n▪ defend the Constitution and laws of the United States\n▪ obey the laws of the United States\n▪ serve in the U.S. military (if needed)\n▪ serve (do important work for) the nation (if needed)\n▪ be loyal to the United States" },
    { question: "How old do citizens have to be to vote for President?", answer: "eighteen (18) and older" },
    { question: "What are two ways that Americans can participate in their democracy?", answer: "▪ vote\n▪ join a political party\n▪ help with a campaign\n▪ join a civic group\n▪ join a community group\n▪ give an elected official your opinion on an issue\n▪ call Senators and Representatives\n▪ publicly support or oppose an issue or policy\n▪ run for office\n▪ write to a newspaper" },
    { question: "When is the last day you can send in federal income tax forms?", answer: "April 15" },
    { question: "When must all men register for the Selective Service?", answer: "▪ at age eighteen (18)\n▪ between eighteen (18) and twenty-six (26)" },
    { question: "What is one reason colonists came to America?", answer: "▪ freedom\n▪ political liberty\n▪ religious freedom\n▪ economic opportunity\n▪ practice their religion\n▪ escape persecution" },
    { question: "Who lived in America before the Europeans arrived?", answer: "▪ American Indians\n▪ Native Americans" },
    { question: "What group of people was taken to America and sold as slaves?", answer: "▪ Africans\n▪ people from Africa" },
    { question: "Why did the colonists fight the British?", answer: "▪ because of high taxes (taxation without representation)\n▪ because the British army stayed in their houses (boarding, quartering)\n▪ because they didn’t have self-government" },
    { question: "Who wrote the Declaration of Independence?", answer: "(Thomas) Jefferson" },
    { question: "When was the Declaration of Independence adopted?", answer: "July 4, 1776" },
    { question: "There were 13 original states. Name three.", answer: "▪ New Hampshire\n▪ Massachusetts\n▪ Rhode Island\n▪ Connecticut\n▪ New York\n▪ New Jersey\n▪ Pennsylvania\n▪ Delaware\n▪ Maryland\n▪ Virginia\n▪ North Carolina\n▪ South Carolina\n▪ Georgia" },
    { question: "What happened at the Constitutional Convention?", answer: "▪ The Constitution was written.\n▪ The Founding Fathers wrote the Constitution." },
    { question: "When was the Constitution written?", answer: "1787" },
    { question: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.", answer: "▪ (James) Madison\n▪ (Alexander) Hamilton\n▪ (John) Jay\n▪ Publius" },
    { question: "What is one thing Benjamin Franklin is famous for?", answer: "▪ U.S. diplomat\n▪ oldest member of the Constitutional Convention\n▪ first Postmaster General of the United States\n▪ writer of “Poor Richard’s Almanac”\n▪ started the first free libraries" },
    { question: "Who is the 'Father of Our Country'?", answer: "(George) Washington" },
    { question: "Who was the first President?", answer: "(George) Washington" },
    { question: "What territory did the United States buy from France in 1803?", answer: "▪ the Louisiana Territory\n▪ Louisiana" },
    { question: "Name one war fought by the United States in the 1800s.", answer: "▪ War of 1812\n▪ Mexican-American War\n▪ Civil War\n▪ Spanish-American War" },
    { question: "Name the U.S. war between the North and the South.", answer: "▪ the Civil War\n▪ the War between the States" },
    { question: "Name one problem that led to the Civil War.", answer: "▪ slavery\n▪ economic reasons\n▪ states’ rights" },
    { question: "What was one important thing that Abraham Lincoln did?", answer: "▪ freed the slaves (Emancipation Proclamation)\n▪ saved (or preserved) the Union\n▪ led the United States during the Civil War" },
    { question: "What did the Emancipation Proclamation do?", answer: "▪ freed the slaves\n▪ freed slaves in the Confederacy\n▪ freed slaves in the Confederate states\n▪ freed slaves in most Southern states" },
    { question: "What did Susan B. Anthony do?", answer: "▪ fought for women’s rights\n▪ fought for civil rights" },
    { question: "Name one war fought by the United States in the 1900s.", answer: "▪ World War I\n▪ World War II\n▪ Korean War\n▪ Vietnam War\n▪ (Persian) Gulf War" },
    { question: "Who was President during World War I?", answer: "(Woodrow) Wilson" },
    { question: "Who was President during the Great Depression and World War II?", answer: "(Franklin) Roosevelt" },
    { question: "Who did the United States fight in World War II?", answer: "Japan, Germany, and Italy" },
    { question: "Before he was President, Eisenhower was a general. What war was he in?", answer: "World War II" },
    { question: "During the Cold War, what was the main concern of the United States?", answer: "Communism" },
    { question: "What movement tried to end racial discrimination?", answer: "civil rights (movement)" },
    { question: "What did Martin Luther King, Jr. do?", answer: "fought for civil rights\n▪ worked for equality for all Americans" },
    { question: "What major event happened on September 11, 2001, in the United States?", answer: "Terrorists attacked the United States." },
    { question: "Name one American Indian tribe in the United States.", answer: "▪ Cherokee\n▪ Navajo\n▪ Sioux\n▪ Chippewa\n▪ Choctaw\n▪ Pueblo\n▪ Apache\n▪ Iroquois\n▪ Creek\n▪ Blackfeet\n▪ Seminole\n▪ Cheyenne\n▪ Arawak\n▪ Shawnee\n▪ Mohegan\n▪ Huron\n▪ Oneida\n▪ Lakota\n▪ Crow\n▪ Teton\n▪ Hopi\n▪ Inuit" },
    { question: "Name one of the two longest rivers in the United States.", answer: "▪ Missouri (River)\n▪ Mississippi (River)" },
    { question: "What ocean is on the West Coast of the United States?", answer: "Pacific (Ocean)" },
    { question: "What ocean is on the East Coast of the United States?", answer: "Atlantic (Ocean)" },
    { question: "Name one U.S. territory.", answer: "▪ Puerto Rico\n▪ U.S. Virgin Islands\n▪ American Samoa\n▪ Northern Mariana Islands\n▪ Guam" },
    { question: "Name one state that borders Canada.", answer: "▪ Maine\n▪ New Hampshire\n▪ Vermont\n▪ New York\n▪ Pennsylvania\n▪ Ohio\n▪ Michigan\n▪ Minnesota\n▪ North Dakota\n▪ Montana\n▪ Idaho\n▪ Washington\n▪ Alaska" },
    { question: "Name one state that borders Mexico.", answer: "▪ California\n▪ Arizona\n▪ New Mexico\n▪ Texas" },
    { question: "What is the capital of the United States?", answer: "Washington, D.C." },
    { question: "Where is the Statue of Liberty?", answer: "▪ New York (Harbor)\n▪ Liberty Island\n[Also acceptable are New Jersey, near New York City, and on the Hudson (River).]" },
    { question: "Why does the flag have 13 stripes?", answer: "▪ because there were 13 original colonies\n▪ because the stripes represent the original colonies" },
    { question: "Why does the flag have 50 stars?", answer: "▪ because there is one star for each state\n▪ because each star represents a state\n▪ because there are 50 states" },
    { question: "What is the name of the national anthem?", answer: "The Star-Spangled Banner" },
    { question: "When do we celebrate Independence Day?", answer: "July 4" },
    { question: "Name two national U.S. holidays.", answer: "▪ New Year’s Day\n▪ Martin Luther King, Jr. Day\n▪ Presidents’ Day\n▪ Memorial Day\n▪ Independence Day\n▪ Labor Day\n▪ Columbus Day\n▪ Veterans Day\n▪ Thanksgiving\n▪ Christmas" }

];

export default cards;
